### ISSUE TITLE
font-lock-operator-face?

### ISSUE THREAD

**Issue by bk322** [ajc/nginx-mode#14]
I'm on emacs 26.0.50.2 and I don't seem to have `font-lock-operator-face`. I replaced it with `font-lock-function-name-face` and it seems to be working.

**Comment by ajc** [comment]
Ok, should now be fixed in v1.1.5.

**Comment by bk322** [comment]
Thanks. Looks like You missed it in another place: https://github.com/ajc/nginx-mode/blob/v1.1.5/nginx-mode.el#L60

**Comment by ajc** [comment]
ok, fixed too. cheers.
